Let Flask-Session be installed with optional dependencies.
pallets-eco/flask-session pull request #228
Opened 2024-03-21 13:24 UTC by eiriklid

The possible optional groups are `cachelib`, `filesystem`,  `mongodb`, `redis`, `sqlalchemy `and `dev`. `Flask-Session[dev]` installs all optional-dependencies.

2024-03-21 13:28 UTC, eiriklid commented
When I ran `flit install --extras dev` it listed all the dependencies that was listed under `optional-dependencies`.

2024-03-21 14:02 UTC, Lxstr commented
Great thanks! I noticed memcache is missing and looks like I was missing that in rye deps too. Which makes me wonder how my tests were running locally. If you like you can add [pymemcache](https://github.com/pinterest/pymemcache) or I can force push. It seems this library is probably most flexible (compatible with gevent given its all python) and maintained.

2024-03-21 14:08 UTC, eiriklid commented
I wondered about that, because the test failed locally. Would that be an optional as well? I thought memcached was the default mode, but if you like all of them to be optional that is fine.

I have not added anything to docs or changelog as I wasn't sure if that was a task for me or the regular maintainers.

2024-03-21 14:21 UTC, Lxstr commented
I guess filesystem was considered the default originally as cachlib was originally included. Now I have mentioned in docs redis is the recommended backend but i still think better to have the developer consciously choose their backend rather than include libraries that a dev may not need, perhaps if they have a complex auditing process and don't want to have to audit another library.

2024-03-23 13:48 UTC, Lxstr requested changes
Some recommended amendments. Thanks for adding docs

2024-03-23 13:48 UTC, Lxstr commented on docs/installation.rst
> +
I think lines 26 to 32 are probably not needed as you said enough on line 13. Removing this would make it more concise.

2024-03-23 13:48 UTC, Lxstr commented on docs/installation.rst
> +     - ``pymemcache``
here while we should put this one first and also use it in tests and the default client for installation, we should also list the others as they are still compatible

2024-03-23 13:48 UTC, Lxstr commented on docs/installation.rst
> +This will install Flask-Session along with all the optional dependencies listed under the ``dev`` category in ``pyproject.toml``, facilitating a comprehensive development setup.
I think dev here is misleading as it wont actually install all libraries required for development, eg pytest. There is PEP735 still in the works but for now this is covered by the requirements files and rye-dependencies. If you use [all] it makes much more sense as installing all extras. 

You could then delete all of these lines as they are covered in contributing

2024-03-23 13:48 UTC, Lxstr commented on pyproject.toml
> +dev = ["Flask-Session[cachelib, filesystem, memcached, mongodb, redis, sqlalchemy]"]
This can be all

2024-03-23 13:48 UTC, Lxstr commented on docs/installation.rst
> +     - ``pymemcache``
I wonder if the above list on line 44 could be rolled into this table, thereby making it clear what client is being installed and also having a final column for alternative client libraries

2024-03-24 12:13 UTC, merged